project_id = "snhutzqpxhylymkzlhga"

[functions]
[functions.verify_jwt]
verify = false

[functions.cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["authorization", "x-client-info", "apikey", "content-type"]
exposed_headers = [""]