project_id = "snhutzqpxhylymkzlhga"

[functions]
[functions.generate-proposal]
verify_jwt = false

[functions.generate-proposal.cors]
origins = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
headers = ["authorization", "x-client-info", "apikey", "content-type"]