project_id = "snhutzqpxhylymkzlhga"

[functions]
[functions.create-checkout]
verify_jwt = true

[functions.create-checkout.cors]
origins = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
headers = ["authorization", "x-client-info", "apikey", "content-type"]