project_id = "snhutzqpxhylymkzlhga"

[functions]
verify_jwt = false

[[functions.cors]]
origin = "*"
methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
headers = ["authorization", "x-client-info", "apikey", "content-type"]
exposed_headers = [""]